import React from "react";

export const metadata = {
  title: "About",
  description: "Generated by create khairul",
};

function Page() {
  return (
    <div>
      <>Hello About Page !!!!</>
    </div>
  );
}

export default Page;
